### ISSUE TITLE
PostfixAdmin 3.3.8 has just been released

### ISSUE THREAD

**Issue by neuffer** [mailserver2/postfixadmin#11]
PostfixAdmin 3.3.8

Repository: postfixadmin/postfixadmin · Tag: postfixadmin-3.3.8 · Commit: 7d04685 · Released by: DavidGoodwin

    Fix invalid template referenced in broadcast-message.php; see #465
    Fix PostgreSQL boolean issue in setup (unable to add superuser); see #461
    Fix SQL error on password change; see #456
    Add/improve Ukrainian language (thanks: andrew.kudrinov)

**Comment by AndrewSav** [comment]
Closed via https://github.com/mailserver2/postfixadmin/pull/12
