### ISSUE TITLE
New version tag

### ISSUE THREAD

**Issue by SaraSmiseth** [mailserver2/postfixadmin#16]
We use the postfixadmin version to tag our versions and docker images. I want to create a new version with PR #15. The postfixadmin version is still the same.

What tag should I use? I could push the new version with the same tag and override the last one?

What do you think @AndrewSav, @sknight80?

**Comment by neuffer** [comment]
Why don't you ask @DavidGoodwin over at https://github.com/postfixadmin/postfixadmin to  do a release. Normally he is quite good about it - if you prod him a bit that is. Otherwise the version number will stay the same until someone else asks him to do a release, simply because releasing is somehow not on his radar otherwise. :-)

**Comment by DavidGoodwin** [comment]
@neuffer thanks for the name drop ;-) 

@SaraSmiseth are you after a release of what's in 'master' ( see e.g. https://github.com/postfixadmin/postfixadmin/blob/master/CHANGELOG.TXT ) ? 

(What's the purpose of this repository/project? How is it different from postfixadmin/docker? Could the one be folded into the other to avoid duplication of effort?)

**Comment by neuffer** [comment]
Am 4. Dezember 2022 14:05:37 MEZ schrieb David Goodwin ***@***.***>:
>@neuffer thanks for the name drop ;-) 
>
>@SaraSmiseth are you after a release of what's in 'master' ( see e.g. https://github.com/postfixadmin/postfixadmin/blob/master/CHANGELOG.TXT ) ? 
>
>(What's the purpose of this repository/project? How is it different from postfixadmin/docker? Could the one be folded into the other to avoid duplication of effort?)
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mailserver2/postfixadmin/issues/16#issuecomment-1336407293
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
Hi David

mailserver2 is a project which provides the infrastructure for a whole mail server and postfixadmin is one of its core components (besides Postfix itself of course).
😎
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by neuffer** [comment]
> @neuffer thanks for the name drop ;-)

@DavidGoodwin You're welcome. :-) 
Of the mail server projects using postfixadmin, I believe mailserver2 is one of the best implementations available.
It would be great if there would be a bit more interaction/integration the upstream (postfixadmin/you) and this project. 
:-)

> @SaraSmiseth are you after a release of what's in 'master' ( see e.g. https://github.com/postfixadmin/postfixadmin/blob/master/CHANGELOG.TXT ) ?

I believe that is exactly what @SaraSmiseth is looking for.

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/releases/tag/postfixadmin-3.3.12 ?

**Comment by DavidGoodwin** [comment]
(Releasing 3.4 probably requires I talk to a few people first ... I'm not 100% sure it's ready for release.)

**Comment by AndrewSav** [comment]
@DavidGoodwin thank you very much, appreciated, that should do it. @merzi if you have time could you do a new PR with this version please? If you do not I'll do this later.

**Comment by merzi** [comment]
@AndrewSav i start testing the new Version and make a PR later

**Comment by neuffer** [comment]
@DavidGoodwin just released https://github.com/postfixadmin/postfixadmin/releases/tag/postfixadmin-3.3.13
It contains the fix for @merzi

**Comment by AndrewSav** [comment]
Is there anything outstanding here, or can this be closed?

**Comment by merzi** [comment]
I think all is clear an can be closed.

**Comment by SaraSmiseth** [comment]
Yes it can be closed. Thank you everyone.

When I have time I'll look at postfixadmin/docker and do some testing. Maybe we can replace this image.
