### ISSUE TITLE
push to postfixadmin?

### ISSUE THREAD

**Issue by neuffer** [mailserver2/postfixadmin#4]
Hi Sara,
have you ever thought about pushing this work upstream into postfixadmin/postfixadmin ?
Just wondering.
Cheers
   Mike

**Comment by SaraSmiseth** [comment]
Not really. They already have a docker image here: https://github.com/postfixadmin/docker.

**Comment by AndrewSav** [comment]
I'm going to close this, please let me know if there are any further queries
